### ISSUE TITLE
Feature Request: Do not delete old content

### ISSUE THREAD

**Issue by SebastianStehle** [drone-plugins/drone-gh-pages#18]
I would like to see an option to not delete old content. The reason is that I use github pages to host my frontend and I would like to keep old javascript bundles.

**Comment by tboerger** [comment]
If you got a good idea how to keep the old content you could provide a pr :)

**Comment by SebastianStehle** [comment]
I guess you can just remove the --delete flag from the rsync command, when the setting is set, but I have almost no experience with GO

**Comment by anoff** [comment]
@SebastianStehle did you try to bake your bundles into the build pipeline before calling this plugin? Removing the `--delete` flag entirely would create huge gh-pages branches.

**Comment by SebastianStehle** [comment]
I don't get it, sorry

**Comment by anoff** [comment]
> I would like to keep old javascript bundles

check in anything you would like to remain on your website and copy it to the folder that will get synced by this plugin

**Comment by SebastianStehle** [comment]
Yes, but then I have to read everything from the gh-pages repo/folder and the effect is the same like removing the --delete flag.

**Comment by tboerger** [comment]
https://github.com/drone-plugins/drone-gh-pages/pull/29 adds a setting to optionally disable this behavior, after merging the PR you are able to use a setting like this:

```
- name: github pages
  image: plugins/gh-pages
  settings:
    delete: false
    ...
```
