### ISSUE TITLE
CNAME is not being synced

### ISSUE THREAD

**Issue by anoff** [drone-plugins/drone-gh-pages#23]
Currently, a `CNAME` file is not being synced to the pages branch due to issue #3  and the resulting fix #6. Took me a while to figure out that this undocumented _feature_ is to blame for my faulty deploy.

Imo all state should be defined via this plugin, if you want a `CNAME` to exist on gh-pages just create one using `echo "mydomain.com" > CNAME` prior to running this plugin. Having an undocumented feature is a bug as the current behavior is unexpected given the information available in the plugin description.

I would opt for syncing everything and adding a note regarding `CNAME` creation into the docs. If you agree I would PR this change.

**Comment by anoff** [comment]
Any thoughts on this?

**Comment by tboerger** [comment]
I'm not the initial author of this plugin, I have no idea why this gets excluded at all.

**Comment by anoff** [comment]
@tboerger see the issue I referenced. Someone had a use-case that required the CNAME to stick around on the gh-pages branch.
Fixing this behavior would be trivial but I am not sure how you guys want to approach such a breaking change (at least for the guy in #3) now that you are 1.0.0

**Comment by tboerger** [comment]
Hum... Maybe it would be better to sync the cname only if it's not present... Or to prevent a breaking change we could document that a cname file got to be part of the branch as it's ignored. 

The branch got to be created manually anyway.

**Comment by Beanow** [comment]
To avoid breaking changes, I suggest a configuration option to include the CNAME file (and maybe the other hard-coded exclusion .git while we're at it) defaulting to the current behaviour.

In our case the CNAME is also managed by previous build steps, so we'd want to copy it.

On the subject of requiring the branch is created manually, there's another common strategy of not preserving the file history in git. Creating a commit with no parent and force pushing it. (Which, if you consider the gh-pages content as just a reproducible build would make sense.) This approach wouldn't require a branch to be set up, but it would require the CNAME file to be copied every time.

It's a bit of a tangent though so I'll track that suggestion in a new issue.

**Comment by tboerger** [comment]
As long as the default doesn't introduce a breaking change I'm open to it.

**Comment by tboerger** [comment]
https://github.com/drone-plugins/drone-gh-pages/pull/29 adds a setting to optionally enable this behavior, after merging the PR you are able to use a setting like this:

```
- name: github pages
  image: plugins/gh-pages
  settings:
    exclude_cname: false
    ...
```
