### ISSUE TITLE
Option to add `[skip ci]` to commit message

### ISSUE THREAD

**Issue by rohit-smpx** [drone-plugins/drone-gh-pages#26]
I was trying to setup a Cron job in my personal github pages site. Due to it being a user gh-pages site I can't use a branch for content. I got this plugin to work with my setup here: https://github.com/rohit-smpx/rohit-smpx.github.io/

But because the new commit also triggers a build it is possible that it might go into an infinite loop.
For eg if the build step always changes files with build timestamps. So if the commit message could have `[skip ci]` in the message one can avoid that.

I think it will be as simple as adding a `skip_ci` option and adding it to the commit message before returning here https://github.com/drone-plugins/drone-gh-pages/blob/a37651bad6988de6f97afae5c8188c3681f14075/plugin.go#L227

If that sounds good then I'll open a PR with the changes.

**Comment by tboerger** [comment]
Why do you think that is required at all? This plugin is actively used in various places without any infinite loop. The target branch will never trigger any build because a .drone.yml will always be excluded.

**Comment by rohit-smpx** [comment]
Test repo where the build is going in infinite loop: https://github.com/rohit-smpx/test-drone-repo
Drone Builds: https://cloud.drone.io/rohit-smpx/test-drone-repo

I had to cancel the build to stop it from creating more commits. I think this will happen with any docs that have some timestamp or something unique being generated in every build.

Could be I'm using the plugin in an unintended way. But this still shouldn't be happening in any case.

**Comment by rohit-smpx** [comment]
My aim was to create a self updating github pages site using the cron job functionality of Drone. So in that case the source and target branch will be same. For testing I enabled it for push events too. 

I could move the drone.yml to another branch and publish results to master, but a simple `[skip ci]` seems like a better solution.

**Comment by tboerger** [comment]
You are using the plugin wrong, it's not intended to use the same branch for source and target.

**Comment by rohit-smpx** [comment]
Cool. I changed it to execute and publish on different branches. Thanks for clearing this up.
